[package]
name = "db-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
store = { path = "../store" }
tokio = { version = "1.0", features = ["full"] }
redis = { version = "0.25", features = ["aio", "tokio-comp", "streams"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.0", features = ["v4"] }
hex = "0.4"
base64 = "0.22"
prost = "0.12"

[build-dependencies]
prost-build = "0.12"
anyhow = "1.0"
