[package]
name = "geyser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
agave-geyser-plugin-interface = { version = "~2.3" }
anyhow = "1.0.98"
base64 = "0.22.1"
borsh = "0.10.3"
bs58 = "0.5.1"
bytes = "1.10.1"
hex = "0.4.3"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["http1", "server"] }
hyper-util = { version = "0.1.15", features = ["server", "tokio"] }
lazy_static = "1.5.0"
log = "0.4.27"
prometheus = "0.14.0"
prost = "0.12"
redis = { version = "0.32.4", features = ["aio", "tokio-comp"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-logger = "2.3.0"
solana-message = "2.4.0"
solana-pubkey = "2.4.0"
solana-transaction-status = "2.3.4"
thiserror = "1.0.61"
tokio = { version = "1.46.1", features = ["full"] }

[build-dependencies]
anyhow = "1.0"
cargo-lock = "10.1.0"
git-version = "0.3"
prost-build = "0.12"
vergen = { version = "9.0", features = ["build", "rustc"] }
