[package]
name = "geyser"
version = "0.1.0"
edition = "2024"

[dependencies]
agave-geyser-plugin-interface = "1.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
borsh = "1.5.1"
base64 = "0.22.1"
redis = { version = "0.25.4", features = ["tokio-comp"] }
tokio = { version = "1.38.0", features = ["full"] }
bs58 = "0.5.1"
log = "0.4"
solana-logger = "2.0.0"
thiserror = "1.0.61"

[lib]
crate-type = ["cdylib"]
