[package]
name = "stream"
version = "0.1.0"
edition = "2021"

[dependencies]
yellowstone-grpc-client = "1.13.0"
yellowstone-grpc-proto = "1.13.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
futures = "0.3"
tonic = "0.10"
bs58 = "0.5"
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
